### ISSUE TITLE
Add a <ul> in that <nav> maybe ?

### ISSUE THREAD

**Issue by jpochetedmead** [WilnelysR/WilnelysR.github.io#1]
https://github.com/WilnelysR/WilnelysR.github.io/blob/446bcb8555279ea6641c49864467ec837a373364/index.html#L16

 <nav>
    **<ul>**
      <a href="#">About</a>
      <a href="projects.html">Projects</a>
      <a href="hobbies.html">Hobbies</a>
    **</ul>**
    </nav>

**Comment by zachfedor** [comment]
@jpochetedmead You need to read [this article](https://guides.github.com/features/mastering-markdown/) to learn how to write HTML in these comments. Your issue description is not readable.

Also, this issue isn't actually a real issue, you're just nitpicking.

**Comment by zachfedor** [comment]
@WilnelysR feel free to close
